# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
 blog_helper:
    class: BlogBundle\Helpers\BlogHelper
    arguments:
      - "@service_container"
 comment_helper:
    class: BlogBundle\Helpers\CommentHelper
    arguments:
      - "@service_container"
 blogger_blog.twig.extension:
    class: BlogBundle\Twig\Extensions\BlogExtension
    tags:
     - { name: twig.extension }